[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
    [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"
